name: mercari-rival-list

on:
  schedule:
    - cron: "0 0 * * *"   # JST 09:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write Google credentials (from Secrets)
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > "${{ github.workspace }}/creds.json"
      - name: Run script (with xvfb)
        env:
          HEADLESS: "1"
          CREDENTIALS_PATH: "${{ github.workspace }}/creds.json"
        run: |
          xvfb-run -a python scripts/mercari-rival-list.py
